[phases.setup]
aptPkgs = ["libx11-xcb1", "libxcomposite1", "libxdamage1", "libxext6", "libxi6", "libxtst6", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libgbm1", "libasound2", "libpangocairo-1.0-0", "libpango-1.0-0", "libcairo2", "libxrandr2", "libxss1"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"